"""enrich_investor_wide_columns

Revision ID: 44102d918926
Revises: 2dbc8b425ce5
Create Date: 2026-04-26 09:43:05.720623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.db.types
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '44102d918926'
down_revision: Union[str, Sequence[str], None] = '2dbc8b425ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investors', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('investor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('hq_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('hq_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('stages', app.db.types.TextArray(), nullable=False))
    op.add_column('investors', sa.Column('sectors', app.db.types.TextArray(), nullable=False))
    op.add_column('investors', sa.Column('geographies', app.db.types.TextArray(), nullable=False))
    op.add_column('investors', sa.Column('geo_focus', app.db.types.TextArray(), nullable=False))
    op.add_column('investors', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('investment_thesis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('stated_thesis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('revealed_thesis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('investment_tendency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('year_founded', sa.Integer(), nullable=True))
    op.add_column('investors', sa.Column('first_cheque_min', sa.Float(), nullable=True))
    op.add_column('investors', sa.Column('first_cheque_max', sa.Float(), nullable=True))
    op.add_column('investors', sa.Column('first_cheque_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('investors', sa.Column('ticket_size_min', sa.Float(), nullable=True))
    op.add_column('investors', sa.Column('ticket_size_max', sa.Float(), nullable=True))
    op.add_column('investors', sa.Column('source_count', sa.Integer(), nullable=False))
    op.add_column('investors', sa.Column('source_names', app.db.types.TextArray(), nullable=False))
    op.add_column('investors', sa.Column('dedupe_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investors', 'dedupe_confidence')
    op.drop_column('investors', 'source_names')
    op.drop_column('investors', 'source_count')
    op.drop_column('investors', 'ticket_size_max')
    op.drop_column('investors', 'ticket_size_min')
    op.drop_column('investors', 'first_cheque_currency')
    op.drop_column('investors', 'first_cheque_max')
    op.drop_column('investors', 'first_cheque_min')
    op.drop_column('investors', 'year_founded')
    op.drop_column('investors', 'investment_tendency')
    op.drop_column('investors', 'revealed_thesis')
    op.drop_column('investors', 'stated_thesis')
    op.drop_column('investors', 'investment_thesis')
    op.drop_column('investors', 'long_description')
    op.drop_column('investors', 'short_description')
    op.drop_column('investors', 'description')
    op.drop_column('investors', 'geo_focus')
    op.drop_column('investors', 'geographies')
    op.drop_column('investors', 'sectors')
    op.drop_column('investors', 'stages')
    op.drop_column('investors', 'hq_country')
    op.drop_column('investors', 'hq_city')
    op.drop_column('investors', 'investor_type')
    op.drop_column('investors', 'domain')
    op.drop_column('investors', 'website')
    # ### end Alembic commands ###
