"""slug_required_unique

Revision ID: 19c18d5d4db4
Revises: 44102d918926
Create Date: 2026-04-26 09:53:05.607432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.db.types
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '19c18d5d4db4'
down_revision: Union[str, Sequence[str], None] = '44102d918926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investors', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_investors_slug'), 'investors', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investors_slug'), table_name='investors')
    op.alter_column('investors', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
