"""first migration

Revision ID: 2dbc8b425ce5
Revises: 
Create Date: 2026-04-26 08:58:54.491803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.db.types
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '2dbc8b425ce5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_vc_id', sa.Integer(), nullable=True),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rounds', app.db.types.TextArray(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enrichment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investors_external_vc_id'), 'investors', ['external_vc_id'], unique=True)
    op.create_table('portfolio_companies',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vc_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sectors', app.db.types.TextArray(), nullable=False),
    sa.Column('stage', app.db.types.TextArray(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hq', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valuation_usd', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('investment_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_companies_vc_id'), 'portfolio_companies', ['vc_id'], unique=False)
    op.create_table('vc_enrichments',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vc_id', sa.Integer(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', app.db.types.JsonB(), nullable=False),
    sa.Column('depth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch_traces', app.db.types.JsonB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vc_enrichments_vc_id'), 'vc_enrichments', ['vc_id'], unique=True)
    op.create_table('vc_funds',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vc_id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fund_size', sa.Float(), nullable=True),
    sa.Column('fund_size_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vc_funds_vc_id'), 'vc_funds', ['vc_id'], unique=False)
    op.create_table('vc_members',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vc_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expertise', app.db.types.TextArray(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vc_members_vc_id'), 'vc_members', ['vc_id'], unique=False)
    op.create_table('portco_team',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_company_id'], ['portfolio_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portco_team_portfolio_company_id'), 'portco_team', ['portfolio_company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portco_team_portfolio_company_id'), table_name='portco_team')
    op.drop_table('portco_team')
    op.drop_index(op.f('ix_vc_members_vc_id'), table_name='vc_members')
    op.drop_table('vc_members')
    op.drop_index(op.f('ix_vc_funds_vc_id'), table_name='vc_funds')
    op.drop_table('vc_funds')
    op.drop_index(op.f('ix_vc_enrichments_vc_id'), table_name='vc_enrichments')
    op.drop_table('vc_enrichments')
    op.drop_index(op.f('ix_portfolio_companies_vc_id'), table_name='portfolio_companies')
    op.drop_table('portfolio_companies')
    op.drop_index(op.f('ix_investors_external_vc_id'), table_name='investors')
    op.drop_table('investors')
    # ### end Alembic commands ###
