"""Alembic migration environment.

Wires alembic into this repo's `app/` package so that:

- The database URL is sourced from `app.core.config.get_settings().database_url`
  rather than `alembic.ini`. The .env-managed `DATABASE_URL` is the single source
  of truth for the connection string.
- `target_metadata` is `SQLModel.metadata`, so `--autogenerate` diffs the live DB
  against the SQLModel tables defined under `app/<context>/models.py`.
- Every per-context `models.py` module is imported here so its tables are
  registered on `SQLModel.metadata` before autogenerate inspects it. **When you
  add a new bounded context, add its `models` import to `_import_all_models()`.**
"""

from logging.config import fileConfig
from typing import Any

from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel

from alembic import context

from app.core.config import get_settings

# Import every per-context `models` module at module level so SQLModel.metadata
# is fully populated before autogenerate inspects it. Add new contexts here as
# their `app/<context>/models.py` is created.
import app.enrichment.models  # noqa: E402, F401
import app.investors.models  # noqa: E402, F401


def render_item(type_: str, obj: Any, autogen_context: Any) -> Any:
    """
    Tell alembic to add `sqlmodel` and `app.db.types` imports when those types
    appear in autogenerated migrations. Without this, generated migrations
    reference `sqlmodel.sql.sqltypes.AutoString` and `app.db.types.TextArray`
    without importing them, producing files that fail to lint and to import.

    Returning ``False`` lets alembic fall back to its default rendering for
    every other type.
    """
    autogen_context.imports.add("import sqlmodel.sql.sqltypes")
    autogen_context.imports.add("import app.db.types")
    return False


config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = SQLModel.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout, no DB connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live DB connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
